{% set version = "3.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-modelstudio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modelStudio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modelStudio/modelStudio_{{ version }}.tar.gz
  sha256: 435dd5abc2ecf465cc379c5c2b5352457124eb2ae058529ba07e395e28f8a181

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dalex >=2.2.1
    - r-digest
    - r-ibreakdown >=2.0.1
    - r-ingredients >=2.2.0
    - r-jsonlite
    - r-progress
    - r-r2d3
  run:
    - r-base
    - r-dalex >=2.2.1
    - r-digest
    - r-ibreakdown >=2.0.1
    - r-ingredients >=2.2.0
    - r-jsonlite
    - r-progress
    - r-r2d3

test:
  commands:
    - $R -e "library('modelStudio')"           # [not win]
    - "\"%R%\" -e \"library('modelStudio')\""  # [win]

about:
  home: https://modelstudio.drwhy.ai, https://github.com/ModelOriented/modelStudio
  license: GPL-3.0-only
  summary: Automate the explanatory analysis of machine learning predictive models. Generate advanced interactive model explanations in the form of a serverless HTML site with only one line of code. This tool is model-agnostic, therefore compatible with most of the black-box predictive models and frameworks. The main function
    computes various (instance and model-level) explanations and produces a customisable dashboard, which consists of multiple panels for plots with their short descriptions. It is possible to easily save the dashboard and share it with others. Tools for Explanatory Model Analysis unite with tools for Exploratory Data Analysis
    to give a broad overview of the model behavior.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
